branches:
  only:
  - master

sudo: required
latex: false
pandoc: true
warnings_are_errors: false

language: r
cran: http://cran.rstudio.com
r:
  - 4.1.1

cache:
  directories:
  - "$HOME/.local/share/renv"
  - "$TRAVIS_BUILD_DIR/renv/library"
  - "$HOME/.TinyTeX/"

jobs:
  include:
  - name: Janssen Data Processing
    env:
    - REPORT_TYPE=IMMUNO
    - TRIAL=janssen_pooled_mock
    script:
    - echo "Processing data"
    - make data_processed
  - name: Moderna Immuno Report
    env:
    - REPORT_TYPE=IMMUNO
    - TRIAL=moderna_mock
    script:
    - echo "Building immunogenicity report"
    - make data_processed
    - make immuno_report
  - name: Janssen Pooled Immuno Report
    env:
    - REPORT_TYPE=IMMUNO
    - TRIAL=janssen_pooled_mock
    script:
    - echo "Building immunogenicity report"
    - make data_processed
    - make immuno_report
  - name: Janssen Pooled Risk Score Report
    env:
    - REPORT_TYPE=RISK
    - TRIAL=janssen_pooled_mock
    script:
    - echo "Building risk score report"
    - make risk_report

apt_packages:
  - libxml2-dev
  - libssl-dev
  - libcurl4-openssl-dev

before_install:
  - sudo apt-get install -y texlive-extra-utils ghostscript

install:
  - cd .. && Rscript -e "install.packages(c('here', 'tinytex'))"
  - wget https://cran.r-project.org/src/contrib/Archive/renv/renv_0.14.0.tar.gz
  - R CMD INSTALL renv_0.14.0.tar.gz
  - echo insecure >> ~/.curlrc && Rscript -e "tinytex::install_tinytex()"
  - export PATH=$HOME/bin:${PATH}
  - cd $TRAVIS_BUILD_DIR && Rscript -e "renv::restore()"

after_script:
  - chmod +x _deploy_reports.sh && ./_deploy_reports.sh

notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
    - benkeser@emory.edu
    - nh@nimahejazi.org

env:
  global:
    secure: VNqbsqmxsR4xZFbEwtSJLSDVTNHW2Llpam67GqW/7P1K11RbF9jpMeng7Tw6Xl2B2gZu06JzmOH6EUxzURzfoTN/jRu6v9lphrJQRbbxeu0OL6f6aTR91CCUV7ptRqBtWT5XI9/l8aE8IOs8MislUZw1YHX/LXtdH/t6txyRKIKCWfrCn219dHpDxhCAeGEEyONUqNgxSj6AOn3zkBqfKElkHRb+KxysjekJBELdP1YMKQN0cpiW6oo9B+3SYVIsON4UBCMpLAzk8hY1LOynHcWeOwYZclBgX8Q1+8ENl/01l+lXh8DZgs+0jSTbfVVzLD+/eyxMyzkVHmrT9xpZXYyA7CRVIMJIWdfSK+MM81hkEgR8aWApVEHrey7qZlLkHDsSRUMkNoOzOxPZo0XABLnUovBwN/2W/qCbLB8OezvlQ6APP8/sOLSO7hu0udymVPGrRPF4nAQXg7evNj0pIK8kYooOez6Iwf8y9hP+tuYdkxrikVw1K0D0v1URfITdT6neng8OQQtqrMqQxAsc8DrxkFChUs8EdHanA8YeHc+Ild4W4kcL3c2atFDvtw7O+5OHL5cMhBCORqJoQIfxWJR/ug25rg/WEkiAXZQVJsxbKW7Lmnp9x6DnRzpWJEezCu4vsMT3uxjg0bJQtBERkX4w+MdLGeWGIZUQU7N6y7M=
