default: &default
  is_ows_trial: no
  case_cohort: no
  make_riskscore: no

ows_trial: &ows_trial
  forestplot_script: cor_coxph_forestplots_ows.R
  is_ows_trial: yes
  case_cohort: yes
  make_riskscore: yes


moderna_trial: &moderna_trial
  <<: *ows_trial
  two_marker_timepoints: yes
  timepoints: [29, 57]
  subset_variable: None
  subset_value: All
  assays: [bindSpike, bindRBD, pseudoneutid50, pseudoneutid80, liveneutmn50]
  assay_labels: [Binding Antibody to Spike, Binding Antibody to RBD, PsV Neutralization 50% Titer, PsV Neutralization 80% Titer, Live Virus Micro Neut 50% Titer]
  assay_labels_short: [Anti Spike IgG (BAU/ml), Anti RBD IgG (BAU/ml), Pseudovirus-nAb ID50 (IU50/ml), Pseudovirus-nAb ID80 (IU80/ml), Live Virus-mnAb ID50 (IU50/ml)]
  times: [B, Day29, Day57, Delta29overB, Delta57overB, Delta57over29]
  time_labels: [Day 1, Day 29, Day 57, D29 fold-rise over D1, D57 fold-rise over D1, D57 fold-rise over D29]

moderna_real: &moderna_real
  <<: *moderna_trial
  mapped_data: /trials/covpn/p3001/analysis/correlates/Part_A_Blinded_Phase_Data/adata/P3001ModernaCOVEimmunemarkerdata_correlates_originaldatafromModerna_v1.0_Oct28_2021.csv # raw data
  study_name: COVE

moderna_boost: &moderna_boost
  mapped_data: /trials/covpn/p3001/analysis/mapping_immune_correlates/Part_C_Unblinded_Phase_Data/adata/COVID_Moderna_stage2_mapped_20230912.csv
  assay_metadata: ../correlates_reporting3/assay_metadata/moderna_boost_assay_metadata.csv
  study_name: COVEBoost

moderna_mock: &moderna_mock
  <<: *moderna_trial
  mapped_data: COVID_VEtrial_practicedata_primarystage1.csv
  study_name: MockCOVE


# vat08_combined and vat08_nAb both includes both Stage 1 monovalent and 2 bivalent trials
vat08_combined: &vat08_combined
  <<: *ows_trial
  # mapped_data: /trials/covpn/p3005/analysis/mapping_immune_correlates/combined/adata/COVID_Sanofi_stage1and2_mapped_20231030.csv # batch 1 only
  # mapped_data: /trials/covpn/p3005/analysis/mapping_immune_correlates/combined/adata/COVID_Sanofi_stage1and2_mapped_20231107.csv
  mapped_data: /trials/covpn/p3005/analysis/mapping_immune_correlates/combined/adata/COVID_Sanofi_stage1and2_mapped_20231213.csv
  assay_metadata: ../correlates_reporting2/assay_metadata/vat08_combined_assay_metadata.csv
  two_marker_timepoints: yes
  timepoints: [22, 43]
  times: [B, Day22, Day43, Delta22overB, Delta43overB, Delta43over22]
  time_labels: [Day 1, Day 22, Day 43, D22 fold-rise over D1, D43 fold-rise over D1, D43 fold-rise over D22]
  study_name: VAT08

covail: &covail
  mapped_data: /trials/covpn/COVAILcorrelates/analysis/mapping_immune_correlates/adata/covail_mapped_data_12222023.csv
  assay_metadata: ../correlates_reporting2/assay_metadata/covail_assay_metadata.csv
  two_marker_timepoints: no
  timepoints: [15]
  times: [B, Day15, Delta15overB]
  time_labels: [Day 1, Day 15, D15 fold-rise over D1]
  study_name: COVAIL


id27hpv: &id27hpv
  mapped_data: /networks/cavd/Objective 4/GH-VAP/ID27-Sankaranarayanan/analysis/mapping_immune_correlates/adata/ID27_IARC_HPV_mapped_20231209.csv
  assay_metadata: ../correlates_reporting2/assay_metadata/id27hpv_assay_metadata.csv
  two_marker_timepoints: no
  timepoints: [18]
  times: [M18]
  time_labels: [Month 18]
  study_name: IARC_HPV


prevent19: &prevent19 # note that RBD is added as a special step and is not included in the config
  <<: *ows_trial
  two_marker_timepoints: no
  timepoints: [35]
  times: [B, Day35, Delta35overB]
  time_labels: [Day 1, Day 35, D35 fold-rise over D1]
  mapped_data: /trials/covpn/p3004/analysis/mapping_immune_correlates/adata/stage1/COVID_Novavax_realdata_20220506.csv 
  assays: [bindSpike, pseudoneutid50]
  assay_labels: [Binding Antibody to Spike, PsV Neutralization 50% Titer]
  assay_labels_short: [Anti Spike IgG (BAU/ml), Pseudovirus-nAb ID50 (IU50/ml)]
  study_name: PREVENT19
  
prevent19_stage2: &prevent19_stage2
  <<: *ows_trial
  two_marker_timepoints: no
  timepoints: [35]
  times: [Day35]
  time_labels: [Day 35]
  mapped_data: /trials/covpn/p3004/analysis/mapping_immune_correlates/stage2/adata/COVID_Novavax_stage2_mapped_20231101.csv 
  assay_metadata: ../correlates_reporting2/assay_metadata/prevent19_stage2_assay_metadata.csv
  study_name: PREVENT19

  
azd1222_base: &azd1222_base
  <<: *ows_trial
  two_marker_timepoints: yes
  timepoints: [29, 57]
  times: [B, Day29, Day57, Delta29overB, Delta57overB, Delta57over29]
  time_labels: [Day 1, Day 29, Day 57, D29 fold-rise over D1, D57 fold-rise over D1, D57 fold-rise over D29]
  mapped_data: /trials/covpn/p3002/analysis/mapping_immune_correlates/adata/COVID_AstraZeneca_realdata_20221208.csv 
  subset_variable: None
  subset_value: All
  study_name: AZD1222

azd1222: &azd1222
  <<: *azd1222_base
  assays: [pseudoneutid50]
  assay_labels: [PsV Neutralization 50% Titer]
  assay_labels_short: [Pseudovirus-nAb ID50 (IU50/ml)]

azd1222_bAb: &azd1222_bAb
  <<: *azd1222_base
  assays: [bindSpike]
  assay_labels: [Binding Antibody to Spike]
  assay_labels_short: [Anti Spike IgG (BAU/ml)]



###################################################################################
# ENSEMBLE part A, EUA, and mock datasets

janssen_trial: &janssen_trial
  <<: *ows_trial
  two_marker_timepoints: no
  timepoints: [29]
  times: [B, Day29, Delta29overB]
  time_labels: [Day 1, Day 29, D29 fold-rise over D1]



## ENSMEMBLE part A datasets
## 0529 mapped dataset is used for severe COVID correlates manuscript

janssen_trial_partA: &janssen_trial_partA
  <<: *janssen_trial
  mapped_data: /trials/covpn/p3003/analysis/mapping_immune_correlates/adata/COVID_ENSEMBLE_realdata_PartAComplete_20230529.csv 
  assays: [bindSpike, bindRBD, pseudoneutid50, pseudoneutid50uncensored, ADCP]
  assay_labels: [Binding Antibody to Spike, Binding Antibody to RBD, PsV Neutralization 50% Titer, PsV Neutralization 50% Titer 2, Phagocytic Score]
  assay_labels_short: [Anti Spike IgG (BAU/ml), Anti RBD IgG (BAU/ml), Pseudovirus-nAb ID50 (IU50/ml), Pseudovirus-nAb ID50 2 (IU50/ml), Phagocytic Score]
  study_name: ENSEMBLE

janssen_pooled_partA: 
  <<: *janssen_trial_partA
  subset_variable: None
  subset_value: All

janssen_na_partA: 
  <<: *janssen_trial_partA
  subset_variable: Region
  subset_value: 0

janssen_la_partA: 
  <<: *janssen_trial_partA
  subset_variable: Region
  subset_value: 1

janssen_sa_partA: 
  <<: *janssen_trial_partA
  subset_variable: Region
  subset_value: 2


## ENSMEMBLE part A datasets for variants analysis
## endpoints without VL are censored
## Analysis will be repeated for variants so no region-specific datasets are needed
## In addition to having variants ID50 data, the new mapped dataset also has updated ancestral ID50 and about 25 new ancestral ID50 data in the subchort

janssen_partA_VL: 
  inherits: janssen_trial_partA
  mapped_data: /trials/covpn/p3003/analysis/mapping_immune_correlates/adata/COVID_ENSEMBLE_PartAComplete_variant_mapped_20230904.csv 
  subset_variable: None
  subset_value: All
  assay_metadata: ../correlates_reporting2/assay_metadata/janssen_partA_VL_assay_metadata.csv

# janssen_na_partA_VL: 
#   <<: *janssen_trial_partA
#   subset_variable: Region
#   subset_value: 0
# 
# janssen_la_partA_VL: 
#   <<: *janssen_trial_partA
#   subset_variable: Region
#   subset_value: 1
# 
# janssen_sa_partA_VL: 
#   <<: *janssen_trial_partA
#   subset_variable: Region
#   subset_value: 2


# ENSMEMBLE EUA datasets

janssen_trial_EUA: &janssen_trial_EUA
  <<: *janssen_trial
  mapped_data: /trials/covpn/p3003/analysis/mapping_immune_correlates/adata/COVID_ENSEMBLE_realdata_20220310.csv 
  assays: [bindSpike, bindRBD, pseudoneutid50]
  assay_labels: [Binding Antibody to Spike, Binding Antibody to RBD, PsV Neutralization 50% Titer]
  assay_labels_short: [Anti Spike IgG (BAU/ml), Anti RBD IgG (BAU/ml), Pseudovirus-nAb ID50 (IU50/ml)]
  study_name: ENSEMBLE

janssen_pooled_EUA: 
  <<: *janssen_trial_EUA
  subset_variable: None
  subset_value: All

janssen_na_EUA: 
  <<: *janssen_trial_EUA
  subset_variable: Region
  subset_value: 0

janssen_la_EUA: 
  <<: *janssen_trial_EUA
  subset_variable: Region
  subset_value: 1

janssen_sa_EUA: 
  <<: *janssen_trial_EUA
  subset_variable: Region
  subset_value: 2


# ENSMEMBLE mock datasets

janssen_trial_mock: &janssen_trial_mock
  <<: *janssen_trial
  mapped_data: COVID_ENSEMBLE_practicedata.csv # raw data
  assays: [bindSpike, bindRBD]
  assay_labels: [Binding Antibody to Spike, Binding Antibody to RBD]
  assay_labels_short: [Anti Spike IgG (BAU/ml), Anti RBD IgG (BAU/ml)]
  study_name: MockENSEMBLE

janssen_pooled_mock:
  <<: *janssen_trial_mock
  subset_variable: None
  subset_value: All

janssen_na_mock:
  <<: *janssen_trial_mock
  subset_variable: Region
  subset_value: 0

janssen_la_mock:
  <<: *janssen_trial_mock
  subset_variable: Region
  subset_value: 1

janssen_sa_mock:
  <<: *janssen_trial_mock
  subset_variable: Region
  subset_value: 2



profiscov_base: &profiscov_base
  study_name: PROFISCOV
  case_cohort: yes
  mapped_data: /networks/cavd/Objective 4/GH-VAP/ID127-Gast/Data/mapping_immune_correlates/adata/COVID_Butantan_realdata_20221021.csv

profiscov: &profiscov
  <<: *profiscov_base
  two_marker_timepoints: yes
  timepoints: [43,91]
  times: [B, Day43, Day91, Delta43overB, Delta91overB, Delta91over43]
  time_labels: [Day 1, Day 43, Day 91, D43 fold-rise over D1, D91 fold-rise over D1, D91 fold-rise over D43]
  assays: [bindSpike, bindSpike_B.1.1.7, bindSpike_B.1.351, bindSpike_P.1, bindRBD, bindRBD_B.1.1.7, bindRBD_B.1.351, bindRBD_P.1, bindN]
  assay_labels: [Binding Antibody to Spike, Binding Antibody to Spike B.1.1.7, Binding Antibody to Spike B.1.351, Binding Antibody to Spike P.1, Binding Antibody to RBD, Binding Antibody to RBD B.1.1.7, Binding Antibody to RBD B.1.351, Binding Antibody to RBD P.1, Binding Antibody to Nucleocapsid]
  assay_labels_short: [Anti Spike IgG (BAU/ml), Anti Spike B.1.1.7 IgG (BAU/ml), Anti Spike B.1.351 IgG (BAU/ml), Anti Spike P.1 IgG (BAU/ml), Anti RBD IgG (BAU/ml), Anti RBD B.1.1.7 IgG (BAU/ml), Anti RBD B.1.351 IgG (BAU/ml), Anti RBD P.1 IgG (BAU/ml), Anti N IgG (BAU/ml)]

profiscov_lvmn: &profiscov_lvmn
  <<: *profiscov_base
  two_marker_timepoints: no
  timepoints: [43]
  times: [B, Day43, Delta43overB]
  time_labels: [Day 1, Day 43, D43 fold-rise over D1]
  assays: [liveneutmn50]
  assay_labels: [Live Virus Micro Neut 50% Titer]
  assay_labels_short: [Live Virus-mnAb ID50 (IU50/ml)]

  
