default: &default
  is_ows_trial: no
  case_cohort: no

ows_trial: &ows_trial
  forestplot_script: cor_coxph_forestplots_ows.R
  is_ows_trial: yes
  case_cohort: yes


moderna_trial: &moderna_trial
  <<: *ows_trial
  two_marker_timepoints: yes
  timepoints: [29, 57]
  subset_variable: None
  subset_value: All
  assays: [bindSpike, bindRBD, pseudoneutid50, pseudoneutid80, liveneutmn50]
  assay_labels: [Binding Antibody to Spike, Binding Antibody to RBD, PsV Neutralization 50% Titer, PsV Neutralization 80% Titer, Live Virus Micro Neut 50% Titer]
  assay_labels_short: [Anti Spike IgG (BAU/ml), Anti RBD IgG (BAU/ml), Pseudovirus-nAb ID50 (IU50/ml), Pseudovirus-nAb ID80 (IU80/ml), Live Virus-mnAb ID50 (IU50/ml)]
  times: [B, Day29, Day57, Delta29overB, Delta57overB, Delta57over29]
  time_labels: [Day 1, Day 29, Day 57, D29 fold-rise over D1, D57 fold-rise over D1, D57 fold-rise over D29]
  study_name_code: COVE

moderna_real: &moderna_real
  <<: *moderna_trial
  mapped_data: /trials/covpn/p3001/analysis/correlates/Part_A_Blinded_Phase_Data/adata/P3001ModernaCOVEimmunemarkerdata_correlates_originaldatafromModerna_v1.0_Oct28_2021.csv # raw data
  study_name: COVE

moderna_mock: &moderna_mock
  <<: *moderna_trial
  mapped_data: COVID_VEtrial_practicedata_primarystage1.csv
  study_name: MockCOVE


prevent19: &prevent19
  <<: *ows_trial
  two_marker_timepoints: no
  timepoints: [35]
  times: [B, Day35, Delta35overB]
  time_labels: [Day 1, Day 35, D35 fold-rise over D1]
  study_name_code: PREVENT19
  mapped_data: /trials/covpn/p3004/analysis/mapping_immune_correlates/adata/COVID_Novavax_realdata_20220418.csv 
  assays: [bindSpike, pseudoneutid50]
  assay_labels: [Binding Antibody to Spike, PsV Neutralization 50% Titer]
  assay_labels_short: [Anti Spike IgG (BAU/ml), Pseudovirus-nAb ID50 (IU50/ml)]
  study_name: PREVENT19
  
azd1222: &azd1222
  <<: *ows_trial
  two_marker_timepoints: yes
  timepoints: [29, 57]
  times: [B, Day29, Day57, Delta29overB, Delta57overB, Delta57over29]
  time_labels: [Day 1, Day 29, Day 57, D29 fold-rise over D1, D57 fold-rise over D1, D57 fold-rise over D29]
  study_name_code: AZD1222
  mapped_data: /trials/covpn/p3002/analysis/mapping_immune_correlates/adata/COVID_AstraZeneca_realdata_20220425.csv 
  subset_variable: None
  subset_value: All
  assays: [pseudoneutid50]
  assay_labels: [PsV Neutralization 50% Titer]
  assay_labels_short: [Pseudovirus-nAb ID50 (IU50/ml)]
  study_name: AZD1222

janssen_trial: &janssen_trial
  <<: *ows_trial
  two_marker_timepoints: no
  timepoints: [29]
  times: [B, Day29, Delta29overB]
  time_labels: [Day 1, Day 29, D29 fold-rise over D1]
  study_name_code: ENSEMBLE


janssen_trial_real: &janssen_trial_real
  <<: *janssen_trial
  mapped_data: /trials/covpn/p3003/analysis/mapping_immune_correlates/adata/COVID_ENSEMBLE_realdata_20220310.csv 
  assays: [bindSpike, bindRBD, pseudoneutid50]
  assay_labels: [Binding Antibody to Spike, Binding Antibody to RBD, PsV Neutralization 50% Titer]
  assay_labels_short: [Anti Spike IgG (BAU/ml), Anti RBD IgG (BAU/ml), Pseudovirus-nAb ID50 (IU50/ml)]
  study_name: ENSEMBLE

janssen_trial_realADCP: &janssen_trial_realADCP
  <<: *janssen_trial
  mapped_data: /trials/covpn/p3003/analysis/mapping_immune_correlates/adata/COVID_ENSEMBLE_realdata_20220310.csv 
  assays: [ADCP]
  assay_labels: [Phagocytic Score]
  assay_labels_short: [Phagocytic Score]
  study_name: ENSEMBLE

janssen_pooled_real: 
  <<: *janssen_trial_real
  subset_variable: None
  subset_value: All

janssen_pooled_realADCP: 
  <<: *janssen_trial_realADCP
  subset_variable: None
  subset_value: All


janssen_na_real: 
  <<: *janssen_trial_real
  subset_variable: Region
  subset_value: 0

janssen_na_realADCP: 
  <<: *janssen_trial_realADCP
  subset_variable: Region
  subset_value: 0



janssen_la_real: 
  <<: *janssen_trial_real
  subset_variable: Region
  subset_value: 1

janssen_la_realADCP: 
  <<: *janssen_trial_realADCP
  subset_variable: Region
  subset_value: 1



janssen_sa_real: 
  <<: *janssen_trial_real
  subset_variable: Region
  subset_value: 2

janssen_sa_realADCP: 
  <<: *janssen_trial_realADCP
  subset_variable: Region
  subset_value: 2




janssen_trial_mock: &janssen_trial_mock
  <<: *janssen_trial
  mapped_data: COVID_ENSEMBLE_practicedata.csv # raw data
  assays: [bindSpike, bindRBD]
  assay_labels: [Binding Antibody to Spike, Binding Antibody to RBD]
  assay_labels_short: [Anti Spike IgG (BAU/ml), Anti RBD IgG (BAU/ml)]
  study_name: MockENSEMBLE

janssen_pooled_mock:
  <<: *janssen_trial_mock
  subset_variable: None
  subset_value: All

janssen_na_mock:
  <<: *janssen_trial_mock
  subset_variable: Region
  subset_value: 0

janssen_la_mock:
  <<: *janssen_trial_mock
  subset_variable: Region
  subset_value: 1

janssen_sa_mock:
  <<: *janssen_trial_mock
  subset_variable: Region
  subset_value: 2
